# Generated by Django 4.2.2 on 2023-06-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_schedult'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
