# Generated by Django 4.2.2 on 2023-06-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_course_discount_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(),
        ),
    ]
