# Generated by Django 4.2.2 on 2023-06-16 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('program', models.TextField()),
                ('result', models.TextField()),
                ('duration_months', models.IntegerField()),
                ('duration_lesson_minutes', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('course_logo_16', models.CharField(max_length=255)),
                ('course_logo_32', models.CharField(max_length=255)),
                ('course_logo_48', models.CharField(max_length=255)),
                ('course_logo_100', models.CharField(max_length=255)),
                ('course_banner', models.CharField(max_length=255)),
                ('additional_info', models.TextField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.category')),
            ],
        ),
    ]
