# Generated by Django 4.2.2 on 2023-06-16 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_course_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('enrollment_date', models.DateTimeField(unique=True)),
                ('enrollment_duration', models.DurationField(unique_for_date=True, unique_for_month=True, unique_for_year=True)),
                ('enrollment_description', models.TextField()),
                ('additional_info', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course')),
            ],
        ),
    ]
